import 'dotenv/config';
import app from './src/app.js';
import { connectDatabase } from './src/config/database.js';
import { createServer } from 'node:http';
import { attachMultiplayer } from './src/routes/socket.js';
const port = process.env.PORT || 3000;
const server = createServer(app);
attachMultiplayer(server);
server.listen(port, '0.0.0.0', () => console.log(`Playroom: http://localhost:${port}`));
connectDatabase();
process.on('SIGTERM', () => server.close(() => process.exit(0)));
